# Generated by Django 2.1.4 on 2018-12-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteins', models.IntegerField(max_length=4)),
                ('carbohydrates', models.IntegerField(max_length=4)),
                ('fat', models.IntegerField(max_length=4)),
            ],
        ),
    ]
