# Generated by Django 2.1.4 on 2019-02-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='calories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
